---
- name: install anyenv
  become: no
  git:
    repo: https://github.com/riywo/anyenv
    dest: ~/.anyenv

- name: add PATH
  become: no
  lineinfile:
    line: export PATH="$HOME/.anyenv/bin:$PATH"
    dest: "~/.bashrc"

- name: add anyenv eval
  become: no
  lineinfile:
    line: eval "$(anyenv init -)"
    dest: "~/.bashrc"

- name: install nodenv
  become: no
  shell: anyenv install nodenv

- name: create default-packages
  become: no
  shell: touch ~/.anyenv/envs/nodenv/default-packages

- name: install node version
  become: no
  command: nodenv install {{ node_version }}

- name: set global node version
  become: no
  shell: nodenv global {{ node_version }}

- name: install pyenv
  become: no
  shell: anyenv install pyenv
