FROM mysql:lasest

# Install dependencies
RUN apt update \
  && apt-get -y python3.8 \
  && apt-get -y install procps python3-magic \
  && apt-get -y install vim git \
  && apt-get -y clean \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip \
  && pip install -U "discord.py[voice]"

RUN cd /home \
  && git clone https://github.com/mo9mo9study/discord.VCtimeRecord.git